version: "3.8"

services:
  es01:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: es01
    networks:
      - elastic
    ports:
      - "9200:9200"
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    mem_limit: ${MEM_LIMIT}

  kib01:
    image: docker.elastic.co/kibana/kibana:${STACK_VERSION}
    container_name: kib01
    networks:
      - elastic
    ports:
      - "5601:5601"
    depends_on:
      - es01
    mem_limit: ${MEM_LIMIT}
    restart: always

networks:
  elastic:
    driver: bridge
